cookie:
  expiry_days: 30
  key: 2e6e34a76bead69934da8e739ea37bee
  name: cookie
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: $2b$12$PPqsa3fwvoUhJ5DfDbwx9uSD52XjIRXURT6rnSPaBibm72llOKJSO
      roles:
      - admin
      - editor
      - viewer
